In [3]:
%matplotlib qt
from matplotlib import pyplot as plt
from numpy.random import rand
from skimage.io import imread, imsave
from skimage.color import rgb2gray
from skimage import img_as_uint
from skimage.util import img_as_float, img_as_ubyte, invert
from skimage.transform import rotate
from skimage.filters import gaussian as ski_gaussian
from pylab import ginput
from scipy.signal import convolve, convolve2d, correlate2d
from scipy.signal import  gaussian as scipy_gaussian
import numpy as np
import os
os.chdir("../Mats")


Example 1.1

In [ ]:
A = imread('bigben.png')
print(type(A))
print(A.shape)
print(A.dtype)
imsave('testimage.jpg',A)

<class 'numpy.ndarray'>
(480, 640, 3)
uint8


Example 1.2

In [5]:
A = imread('cameraman.tif')
plt.figure(1)
plt.imshow(A)

plt.figure(2)
plt.axis('off')
plt.imshow(A,cmap='gray')
plt.show()

Example 1.3

In [ ]:
B = rand(256,256)*125
plt.figure(1)
plt.axis('off')
plt.imshow(B,cmap='gray')
plt.colorbar()

plt.figure(2)
plt.axis('off')
plt.imshow(B,vmin=0,vmax=255,cmap='gray')
plt.colorbar()
plt.show()

Example 1.4

In [6]:
img = 'cell.tif'
img2 = 'DeltaE_16bit_gamma2.2.tif'
img3 = 'onion.png'

# img = "mat1.jpg"
# img2 = "mat2.jpg"
# img3 = "mat3.jpg"

# img = "1h_B1.tif"
# img2 = "1h_B2.tif"
# img3 = "mat3.jpg"


B = imread(img)
print(B.shape,B.dtype)
C = imread(img2)
print(C.shape,C.dtype)
D = imread(img3)
print(D.shape,D.dtype)

plt.subplot(3,1,1)
plt.imshow(B,cmap='jet')
plt.axis('off')

plt.subplot(3,1,2)
plt.imshow(C, cmap='gray')
plt.axis('off')
plt.subplot(3,1,3)
plt.imshow(D)
plt.show()

(159, 191) uint8
(2048, 3072, 3) uint16
(135, 198, 3) uint8


Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


Example 1.5

In [ ]:
plt.imshow(img_as_float(C),cmap='gray')
plt.axis('off')
plt.show()

Example 1.6

In [ ]:
print(B[500:600][45:55])

[]


In [8]:
B = imread(img)

plt.figure(1)
plt.imshow(B, cmap='gray')

plt.figure(2)
plt.imshow(D)

print('Click on 3 points in the image')
coord = ginput(3)
print('You clicked: ' + str(coord))
# print pixel value at location (25,50)
print(B[25,50])
# set pixel value at (25,50) to white
B[25,50]= 255;
# view resulting changes in image
plt.figure(3)
plt.imshow(B, cmap='gray')
# print RGB pixel value at location (25,50)
print(D[25,50,:])
# print only the red value at (25,50)
print(D[25,50,0])
D[25,50,:] = [255, 255, 255]; # set pixel value to RGB white
plt.figure(4)
plt.imshow(D)
plt.show()

Click on 3 points in the image
You clicked: [(89.71774193548384, 42.48951612903225), (132.83064516129028, 72.82822580645161), (68.95967741935482, 98.3766129032258)]
46
[57 41 48]
57


Example 1.7

In [ ]:
D = imread(img3)
D_read_as_gray = imread(img3, as_gray=True)
D_naive_gray = 1/3*+(D[:,:,0]+D[:,:,1]+D[:,:,2])
D_better_gray = 0.2989*D[:,:,0] + 0.5870*D[:,:,1] + 0.1140*D[:,:,2]
plt.subplot(2,2,1)
plt.title("Original")
plt.imshow(D)

plt.subplot(2,2,2)
plt.title("Read as grey")
plt.imshow(D_read_as_gray)

plt.subplot(2,2,3)
plt.title("Naive gray")
plt.imshow(D_naive_gray)

plt.subplot(2,2,4)
plt.title("Bettergrey")
plt.imshow(D_better_gray)

plt.show()

Example 1.8

In [ ]:
D = imread(img3)
Dred = D[:,:,0]
Dgreen = D[:,:,1]
Dblue = D[:,:,2]

plt.subplot(2,2,1)
plt.imshow(D)

plt.subplot(2,2,2)
plt.imshow(Dred)
plt.title("Red")

plt.subplot(2,2,3)
plt.imshow(Dgreen)
plt.title("Green")

plt.subplot(2,2,4)
plt.imshow(Dblue)
plt.title("Blue")

plt.show()


Example 1.9

In [ ]:
I = imread("cameraman.tif")
plt.imshow(I, cmap="gray")
x = [100, 100, 230]
y = [100, 200, 200]

plt.plot(x, y, 'r*')

plt.plot(x[::2], y[::2], "g-")
plt.show()
print(y[::2])

[100, 200]


Exercise 1.1

In [3]:
I = imread("cell.tif")
I_1, I_2 = np.copy(I), np.copy(I)
c = 100
I_1[100, 20] = np.clip(I_1[20, 100].astype('int16')+c,0, 255).astype('uint8')
I_2[100, 20] = np.clip(I_2[20, 100].astype('int16')-c,0, 255).astype('uint8')
J = np.clip(I.astype('int16')+c, 0, 255).astype('uint8')
K = np.clip(I.astype('int16')-c, 0, 255).astype('uint8')
plt.subplot(2, 3, 1)
plt.imshow(I, cmap="gray")
plt.title("Original")

plt.subplot(2,3,2)
plt.imshow(I_1, cmap="gray")
plt.title("1 +")

plt.subplot(2, 3, 3)
plt.imshow(I_2, cmap="gray")
plt.title("1 -")
plt.subplot(2,3,4)
plt.imshow(J, cmap="gray")
plt.title("all +")

plt.subplot(2, 3, 5)
plt.imshow(K, cmap="gray")
plt.title("all -")

Text(0.5, 1.0, 'all -')

Exercise 1.2

In [4]:
I = imread("cell.tif")
def add_constant(img, c):
    I = np.copy(img)
    return np.clip(I.astype('int32')+c, 0, 255).astype(I.dtype)
J = add_constant(I, 25)
plt.imshow(J, cmap="gray")
plt.axis("off")

(-0.5, 190.5, 158.5, -0.5)

Exercise 1.3

In [8]:
I = imread("cell.tif")
plt.subplot(2, 2, 1)
plt.imshow(I, cmap="gray")
plt.title("gray")

plt.subplot(2,2,2)
plt.imshow(I, cmap="viridis")
plt.title("viridis")

plt.subplot(2, 2, 3)
plt.imshow(I, cmap="cool")
plt.title("cool")
plt.subplot(2,2,4)
plt.imshow(I, cmap="Purples")
plt.title("Purples")
plt.show()

Text(0.5, 1.0, 'Purples')

Exercise 1.4

In [12]:
A = imread('cameraman.tif')
imsave('cameraman.jpg',A)
imsave('cameraman.png',A)

B = imread('cameraman.jpg')
C = imread('cameraman.png')
abs_diff = np.abs(B-C)
plt.subplot(1, 3, 1)
plt.imshow(B, cmap="gray")

plt.subplot(1, 3, 2)
plt.imshow(C, cmap="gray")

plt.subplot(1, 3, 3)
plt.imshow(abs_diff, cmap="gray")

plt.show()

Example 2.1

In [ ]:
f = np.ones(64)
f = f/sum(f)

g = convolve(f,f)
g = g / sum(g)

h = convolve(g,g)
h = h / sum(g)

j = convolve(h,h)
j = j / sum(j)


plt.subplot(2,2,1)
plt.plot(f,'k-')
plt.axis('off')
plt.subplot(2,2,2)
plt.plot(g,'k-')
plt.axis('off')
plt.subplot(2,2,3)
plt.plot(h,'k-')
plt.axis('off')
plt.subplot(2,2,4)
plt.plot(j,'k-')
plt.axis('off')
plt.show()


Example 2.2

In [7]:
A = img_as_float(imread("trui.png"))
gaussian1d = scipy_gaussian(3, 2)

PSF = np.outer(gaussian1d, gaussian1d)
print(PSF)
motionWidth = 21
h = np.zeros((motionWidth, motionWidth))
h[motionWidth//2, :] = 1
h = rotate(h, 45).astype(float)
h = h /np.sum(h)

B = convolve2d(PSF, A)
C = convolve2d(A, h)
D = convolve2d(A, A)
E = correlate2d(A, A)

plt.subplot(2, 3, 1)
plt.imshow(A, cmap="gray")

plt.subplot(2, 3, 2)
plt.imshow(B, cmap="gray")

plt.subplot(2, 3, 3)
plt.imshow(C, cmap="gray")

plt.subplot(2, 3, 4)
plt.imshow(D, cmap="gray")

plt.subplot(2, 3, 5)
plt.imshow(E, cmap="gray")

plt.show()

[[0.77880078 0.8824969  0.77880078]
 [0.8824969  1.         0.8824969 ]
 [0.77880078 0.8824969  0.77880078]]


Example 2.3

In [25]:
A = imread("cameraman.tif")
rows, cols = A.shape

Abuild = np.zeros(A.shape)
sub = rand(rows, cols) < 0.50
Abuild[sub] = A[sub]
B10 = ski_gaussian(Abuild, sigma=2)
plt.subplot(1,2,1)
plt.axis("off")
plt.imshow(Abuild, cmap="gray")
plt.colorbar()
plt.title("Object points")

plt.subplot(1,2,2)
plt.axis("off")
plt.imshow(B10, cmap="gray")
plt.colorbar()
plt.title("Response of LSI system")
plt.show()


Exercise 2.1

When 15% of points are selected the rough details of the picture can be seen. Above 50% the picture starts to get coherents. By increasing the sigma in the gaussian the picture gets more blurry as each pixel shown gets ligth from more input pixels.

Example 3.1

In [26]:
A = imread("cameraman.tif")
plt.subplot(1, 3, 1)
plt.imshow(A, cmap="gray")
plt.axis("off")

B = A + 100
plt.subplot(1, 3, 2)
plt.imshow(B, cmap="gray")
plt.axis("off")

C = np.clip(A.astype("uint16")+100, 0, 255).astype("uint8")
plt.subplot(1, 3, 3)
plt.imshow(C, cmap="gray")
plt.axis("off")

plt.show()

Example 3.2 - 3.4

In [4]:
A = imread("cola1.png")
B = imread("cola2.png")

plt.subplot(2, 3, 1)
plt.imshow(A)

plt.subplot(2, 3, 2)
plt.imshow(B)
output = np.clip(A-B, 0, 255)
output2 = img_as_ubyte(np.clip(A.astype("int16")-B, 0, 255))

plt.subplot(2, 3, 3)
plt.imshow(output)

plt.subplot(2, 3, 4)
plt.imshow(output2)

output3 = img_as_ubyte(np.clip(np.absolute(A.astype("int16")-B), 0, 255))
plt.subplot(2, 3, 5)
plt.imshow(output3)

plt.figure()
plt.subplot(1, 3, 1)
plt.imshow(A)

output = A*1.5
plt.subplot(1, 3, 2)
plt.imshow(output.astype("uint8"))

output2 = A/4
plt.subplot(1, 3, 3)
plt.imshow(output2.astype("uint8"))
plt.show()

d:\Anaconda\AnacondaInstall\envs\py310\lib\site-packages\skimage\util\dtype.py:541: UserWarning: Downcasting int16 to uint8 without scaling because max value 130 fits in uint8
  return _convert(image, np.uint8, force_copy)
d:\Anaconda\AnacondaInstall\envs\py310\lib\site-packages\skimage\util\dtype.py:541: UserWarning: Downcasting int16 to uint8 without scaling because max value 217 fits in uint8
  return _convert(image, np.uint8, force_copy)


Example 3.5

In [5]:
C = imread("DeltaE_16bit_gamma2.2.tif")
print(C.shape, C.dtype)

Cscaled = C.astype("float32")/C.max()
Cscaled2 = img_as_float(C)

plt.subplot(1, 3, 1)
plt.imshow(C)
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(Cscaled)
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(Cscaled2)
plt.axis("off")

plt.show()

Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


(2048, 3072, 3) uint16


Example 3.6

In [7]:
A = imread("cameraman.tif")
plt.subplot(1, 3, 1)
plt.imshow(A, cmap="gray")

B1 = np.invert(A)
B2 = invert(A)

plt.subplot(1, 3, 2)
plt.imshow(B1, cmap="gray")

plt.subplot(1, 3, 3)
plt.imshow(B2, cmap="gray")

plt.show()

Example 3.7

In [9]:
A = imread("toycars1.png")
B = imread("toycars2.png")

plt.subplot(4, 3, 1), plt.imshow(A)
plt.subplot(4, 3, 2), plt.imshow(B)
plt.subplot(4, 3, 4), plt.imshow(np.abs(A-B))
D = np.clip(np.abs(A.astype("int16")-B), 0, 255).astype("uint8")
plt.subplot(4, 3, 5), plt.imshow(D)

E = img_as_uint(np.abs(A.astype("int16")-B))
plt.subplot(4, 3, 6), plt.imshow(E)

Abw = np.where(rgb2gray(A) <= 0.5, 0, 1)
Bbw = np.where(rgb2gray(B) <= 0.5, 0, 1)
plt.subplot(4, 3, 7), plt.imshow(Abw)
plt.subplot(4, 3, 8), plt.imshow(Bbw)

output = Abw^Bbw
plt.subplot(4, 3, 9), plt.imshow(output.astype("float"))

plt.show()

Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


Example 3.8

In [12]:
I = img_as_float(imread("circuit.tif"))
thresratio = 0.3
T = np.where(I<= thresratio, 0, 1)
plt.subplot(1, 2, 1), plt.imshow(I, cmap="gray")
plt.subplot(1, 2, 2), plt.imshow(T, cmap="gray")

plt.show()

Example 3.9

In [14]:
I = imread("cameraman.tif")

plt.subplot(2,2,1), plt.imshow(I, vmin=0, vmax=255, cmap="gray")

Id = img_as_float(I)
output1 = 2*np.log(1+Id)
output2 = 3*np.log(1+Id)
output3 = 5*np.log(1+Id)
plt.subplot(2,2,2), plt.imshow(output1, vmin=0, vmax=3.5, cmap="gray")
plt.subplot(2,2,3), plt.imshow(output2, vmin=0, vmax=3.5, cmap="gray")
plt.subplot(2,2,4), plt.imshow(output3, vmin=0, vmax=3.5, cmap="gray")

plt.show()

Example 3.10

In [18]:
I = imread("cameraman.tif")

plt.subplot(2,2,1), plt.imshow(I, vmin=0, vmax=255, cmap="gray")
Id = img_as_float(I)
output1 = 4*(((1+0.3)**(Id))-1)
output2 = 4*(((1+0.4)**(Id))-1)
output3 = 4*(((1+0.6)**(Id))-1)
plt.subplot(2,2,2), plt.imshow(output1, vmin=0, vmax=2.5, cmap="gray")
plt.subplot(2,2,3), plt.imshow(output2, vmin=0, vmax=2.5, cmap="gray")
plt.subplot(2,2,4), plt.imshow(output3, vmin=0, vmax=2.5, cmap="gray")

plt.show()

Example 3.11

In [19]:
I = imread("cameraman.tif")

plt.subplot(2,2,1), plt.imshow(I, vmin=0, vmax=255, cmap="gray")
Id = img_as_float(I)
output1 = 4*(Id**0.5)
output2 = 4*(Id**1.5)
output3 = 4*(Id**3)
plt.subplot(2,2,2), plt.imshow(output1, cmap="gray")
plt.subplot(2,2,3), plt.imshow(output2, cmap="gray")
plt.subplot(2,2,4), plt.imshow(output3, cmap="gray")

plt.show()